### PR TITLE
Add default (in Quarto params) and custom (in metadata) dead bands

### PR DESCRIPTION
**Pull request by bpbond**
See #6

## Example

With default dead band:

Screenshot 2023-01-24 at 4 05 32 AM

With custom dead band of 60 seconds specified in the metadata:

Screenshot 2023-01-24 at 4 06 20 AM

### CODE REVIEW

**Comment by bpbond** [comment]
☝️ fyi @wilsonsj100 I think this addresses your https://github.com/COMPASS-DOE/sw/issues/6#issuecomment-1401238237

**Comment by wilsonsj100** [comment]
That should work! Just to clarify: do do we put in the custom deadband when we are in R or do we have to go back to the meta-data file? Also does the code flag and automatically go back and recalculate that flux or?

**Comment by bpbond** [comment]
There's a default value, but if you see (via QA/QC) that a particular observation needs a different value, e.g. in the example above, right you enter it into the metadata sheet and re-run.

**Comment by bpbond** [comment]
Above, the first figure shows flux model fit with default dead band of 10s; and the second, with a custom 60s dead band.

**Comment by wilsonsj100** [comment]
Ah okay I think I understand that now. We should write that in the code notes / protocol and say that if you have to change the deadband then you should put a note in the notes section. 

Thanks!

**Pull request merged**
